name: Build

on:
  workflow_call:

jobs:
  SourceGen:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore src/FluentReflection.Assembly.EmbeddedResource.SourceGenerator/FluentReflection.Assembly.EmbeddedResource.SourceGenerator.csproj

    - name: Build
      run: dotnet build src/FluentReflection.Assembly.EmbeddedResource.SourceGenerator/FluentReflection.Assembly.EmbeddedResource.SourceGenerator.csproj --no-restore