using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FluentReflection.Assembly.EmbeddedResource.SourceGenerator
{
    internal static class EmbeddedResourceSource
    {
        public static string Namespace = "FluentReflectionEmbeddedResourceGen";
        public static string EmbeddedResourceHelperClassName = "EmbededResourceHelper";
        public static string EmbeddedResourceClassName = "EmbeddedResources";

        public static string Tab = "    ";

        public static string PropertyNameKey = "<PropertyName>";
        public static string ResourcePathKey = "<ResourcePath>";
        public static string CustomNamespaceKey = "<CustomNamespace>";
        public static string CustomPropertiesKey = "<CustomProperties>";
        public static string SubClassNameKey = "<SubClassName>";
        public static string TabKey = "<Tab>";

        public const string AutoGeneratedHeader =
    @"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------";

        public static string EmbeddedResourceTextProp = $"{TabKey}public static string {PropertyNameKey} => {EmbeddedResourceHelperClassName}.Instance.LoadResourceText(\"{ResourcePathKey}\");{Environment.NewLine}";
        public static string EmbeddedResourceByteArrayProp = $"{TabKey}public static byte[] {PropertyNameKey} => {EmbeddedResourceHelperClassName}.Instance.LoadResourceBytes(\"{ResourcePathKey}\");{Environment.NewLine}";
        public static string EmbeddedResourceHelper = $@"
{AutoGeneratedHeader}
using System;
using System.Reflection;
namespace {Namespace}
{{
    public class {EmbeddedResourceHelperClassName}
    {{
        public static {EmbeddedResourceHelperClassName} Instance = new {EmbeddedResourceHelperClassName}();

        public string LoadResourceText(string resourcePath)
        {{
            var assembly = Assembly.GetAssembly(GetType());
            using (Stream stream = assembly.GetManifestResourceStream(resourcePath))
            using (StreamReader reader = new StreamReader(stream))
                return reader.ReadToEnd();
        }}

        public byte[] LoadResourceBytes(string resourcePath)
        {{
            var assembly = Assembly.GetAssembly(GetType());
            using (Stream stream = assembly.GetManifestResourceStream(resourcePath))
            using (BinaryReader br = new BinaryReader(stream))
                return br.ReadBytes((int)stream.Length);
        }}
    }}
}}
";

        public static string EmbeddedResourceSubClassTemplate = $@"
{TabKey}public static partial class {SubClassNameKey}
{TabKey}{{
{CustomPropertiesKey}
{TabKey}}}";

        public static string EmbeddedResourceClassTemplate = $@"
{AutoGeneratedHeader}
using System;
using System.Reflection;
using {Namespace};

namespace {Namespace}.{CustomNamespaceKey};

public static partial class {EmbeddedResourceClassName}
{{
{CustomPropertiesKey}
}}";

    }
}
