name: Build

on:
  workflow_call:

jobs:
  Abstraction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore src/FluentReflection.Abstraction/FluentReflection.Abstraction.csproj

    - name: Build
      run: dotnet build src/FluentReflection.Abstraction/FluentReflection.Abstraction.csproj --no-restore

  Core:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore src/FluentReflection.Core/FluentReflection.Core.csproj

    - name: Build
      run: dotnet build src/FluentReflection.Core/FluentReflection.Core.csproj --no-restore