name: Pipeline

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main" ]

jobs:
  1_FRL:
    uses: TomaszBanas/FluentReflection/.github/workflows/FRL_build.yml@main

  2_FRL:
    needs: 1_FRL
    uses: TomaszBanas/FluentReflection/.github/workflows/FRL_test.yml@main

  3_FRL:
    needs: 2_FRL
    if: github.ref == 'refs/heads/release'
    uses: TomaszBanas/FluentReflection/.github/workflows/FRL_deploy.yml@main


  1_ESG:
    uses: TomaszBanas/FluentReflection/.github/workflows/ESG_build.yml@main

  2_ESG:
    needs: 1_ESG
    uses: TomaszBanas/FluentReflection/.github/workflows/ESG_test.yml@main

  3_ESG:
    needs: 2_ESG
    if: github.ref == 'refs/heads/release'
    uses: TomaszBanas/FluentReflection/.github/workflows/ESG_deploy.yml@main