name: Pipeline

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_FRL:
    uses: TomaszBanas/FluentReflection/.github/workflows/FRL_build.yml@main

  Test_FRL:
    needs: Build_FRL
    uses: TomaszBanas/FluentReflection/.github/workflows/FRL_test.yml@main

  Deploy_FRL:
    needs: Test_FRL
    if: github.ref == 'refs/heads/release'
    uses: TomaszBanas/FluentReflection/.github/workflows/FRL_deploy.yml@main


  Build_ESG:
    uses: TomaszBanas/FluentReflection/.github/workflows/ESG_build.yml@main

  Test_ESG:
    needs: Build_ESG
    uses: TomaszBanas/FluentReflection/.github/workflows/ESG_test.yml@main

  Deploy_ESG:
    needs: Test_ESG
    if: github.ref == 'refs/heads/release'
    uses: TomaszBanas/FluentReflection/.github/workflows/ESG_deploy.yml@main



# name: Pipeline

# on:
#   push:
#     branches: [ "main", "release" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   FluentReflectionLib:
#     uses: ./.github/workflows/fluent_reflection_lib/action.yml@main
  
#   SourceGen:
#     uses: ./.github/workflows/embedded_source_gen/action.yml@main    