name: Pipeline

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_app:
    uses: TomaszBanas/FluentReflection/.github/workflows/build.yml@main
  test:
    needs: build_app
    uses: TomaszBanas/FluentReflection/.github/workflows/test.yml@main
  # deploy:
  #   needs: test
  #   uses: TomaszBanas/FluentReflection/.github/workflows/deploy.yml@main