name: Pipeline

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main" ]

jobs:
  FluentReflectionLib:
    uses: TomaszBanas/FluentReflection/.github/workflows/fluent_reflection_lib/action.yml@main
  
  SourceGen:
    uses: TomaszBanas/FluentReflection/.github/workflows/embedded_source_gen/action.yml@main    