name: Pipeline

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_app:
    uses: TomaszBanas/FluentReflection/.github/workflows/build.yaml@main
  test_app:
    needs: build_app
    uses: TomaszBanas/FluentReflection/.github/workflows/test.yaml@main
  deploy_app:
    needs: test_app
    if: github.ref == 'refs/heads/release'
    uses: TomaszBanas/FluentReflection/.github/workflows/deploy.yaml@main